#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import String

import pyrealsense2 as rs
import numpy as np
import cv2
import os
from datetime import datetime


class CameraNode(Node):

    def __init__(self):
        super().__init__("camera_node")

        os.makedirs("screenshots", exist_ok=True)

        # ---------------- RealSense ----------------
        self.pipeline = rs.pipeline()
        config = rs.config()
        # config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 15)
        config.enable_stream(rs.stream.color, 1280, 720, rs.format.bgr8, 30)

        self.pipeline.start(config)

        # Warmup
        for _ in range(30):
            self.pipeline.wait_for_frames()

        self.get_logger().info("Camera started")

        # ---------------- ROS2 ----------------
        self.done_pub = self.create_publisher(String, "/camera/done", 10)

        self.trigger_sub = self.create_subscription(
            String,
            "/camera/trigger",
            self.trigger_callback,
            10
        )

    def trigger_callback(self, msg):

        if msg.data != "capture":
            return

        self.get_logger().info("Capture requested")

        try:
            frames = self.pipeline.wait_for_frames(timeout_ms=5000)
            color_frame = frames.get_color_frame()

            if not color_frame:
                self.get_logger().error("No frame received")
                return

            image = np.asanyarray(color_frame.get_data())

            filename = datetime.now().strftime("screenshots/image_%Y%m%d_%H%M%S.png")
            cv2.imwrite(filename, image)

            self.get_logger().info(f"Saved {filename}")

        except Exception as e:
            self.get_logger().error(f"Capture failed: {e}")
            return

        # Notify C++ node
        done_msg = String()
        done_msg.data = "done"
        self.done_pub.publish(done_msg)

    def destroy_node(self):
        self.pipeline.stop()
        super().destroy_node()


def main():
    rclpy.init()
    node = CameraNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass

    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()